name: Update main branch

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'main'

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        path: main

    - name: Merge changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git -C main merge ${{ github.ref }} --no-ff --commit --message "Merge from ${{ github.ref }}"

    - name: Push changes
      run: |
        git -C main push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
