name: Automatisation CI/CD

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request_to_main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create Pull Request to main
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        source: "${{ github.ref }}"
        target: "main"
        title: "Update main with changes from ${{ github.ref }}"
        body: "A new commit has been made to ${{ github.ref }}. This pull request is to update the main branch."
        labels: "automerge"

  update_branches_from_main:
    needs: create_pull_request_to_main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Update branches from main
      run: |
        git fetch origin
        BRANCHES=$(git branch -r | grep -v 'main' | grep -v HEAD | sed 's/origin\///')
        for branch in $BRANCHES; do
          git checkout $branch
          git merge origin/main
          git push origin $branch
        done
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
