# .github/workflows/update_branches.yml
name: Update branch when pull request

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  pull-requests: write
  contents: write

jobs:
  update_branches_from_main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Configure Git user
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Update branches from main
      run: |
        git fetch origin
        BRANCHES=$(git branch -r | grep -v 'main' | grep -v HEAD | sed 's/origin\///')
        for branch in $BRANCHES; do
          git checkout $branch
          git merge origin/main --allow-unrelated-histories
          git push origin $branch
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
