# .github/workflows/update.yml
name: Automerge Main on push

on:
  push:
    branches-ignore:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  create_pull_request_to_main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create Pull Request to main
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "${{ github.ref }}"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Update main with changes from ${{ github.ref }}"
        pr_body: "A new commit has been made to ${{ github.ref }}. This pull request is to update the main branch."
        pr_label: "automerge"
